[package]
name = "tagtool"
version = "0.1.0"
description = "Find files by tags"
authors = ["tczyz <tomczyz97@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
color-eyre = "0.6.3"
directories = "6.0.0"
clap = { version = "4.5.42", features = ["cargo", "derive"] }
fuzzy-matcher = "0.3.7"
once_cell = "1.21.3"
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio", "chrono"] }
log = "0.4.27"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
