CREATE TABLE Tags
(
    Id        INTEGER PRIMARY KEY AUTOINCREMENT,
    Text      TEXT UNIQUE,
    CreatedAt DATETIME DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE Files
(
    Id        INTEGER PRIMARY KEY AUTOINCREMENT,
    Path      TEXT NOT NULL UNIQUE,
    Hash      BLOB NULL,
    CreatedAt DATETIME DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE TagsFiles
(
    FileId    INTEGER,
    TagId     INTEGER,
    CreatedAt DATETIME DEFAULT (CURRENT_TIMESTAMP),

    PRIMARY KEY (FileId, TagId),
    FOREIGN KEY (FileId) REFERENCES Files (Id) ON DELETE CASCADE,
    FOREIGN KEY (TagId) REFERENCES Tags (Id) ON DELETE CASCADE
);
