CREATE TABLE Tags
(
    Id        INTEGER PRIMARY KEY AUTOINCREMENT,
    Text      TEXT UNIQUE,
    CreatedAt DATETIME DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE Files

(
    Id        INTEGER PRIMARY KEY AUTOINCREMENT,
    Path      TEXT,
    CreatedAt DATETIME DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE TagsFiles
(
    TagId     INTEGER,
    FileId    INTEGER,
    CreatedAt DATETIME DEFAULT (CURRENT_TIMESTAMP),

    PRIMARY KEY (TagId, FileId),
    FOREIGN KEY (TagId) REFERENCES Tags (Id) ON DELETE CASCADE,
    FOREIGN KEY (FileId) REFERENCES Files (Id) ON DELETE CASCADE
);
